---
name: Delete deployment

on:
  delete:
    branches-ignore:
      - main

jobs:
  delete_resources:
    runs-on: ubuntu-latest
    permissions: write-all

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Setup SSH
        shell: bash
        env:
          SERVER_SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SERVER_SSH_KNOWN_HOSTS: ${{ secrets.SSH_KNOWN_HOSTS }}
        run: |
          mkdir -p ~/.ssh/
          echo "$SERVER_SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          echo "$SERVER_SSH_KNOWN_HOSTS" >> ~/.ssh/known_hosts
          chmod 600 ~/.ssh/known_hosts

      - name: Generate destroy.sql
        uses: cuchi/jinja2-action@v1.2.0
        with:
          template: sql/destroy.sql.j2
          output_file: sql/destroy.sql
          strict: true
          variables: |
            database=${{ github.event.ref }}

      - name: Remove k8s resources
        shell: bash
        run: |
          ssh ${{ secrets.USER }}@${{ secrets.HOSTNAME }} \
          /snap/bin/microk8s kubectl delete all --all -n dirtviz-${{ github.event.ref }} \

      - name: Remove k8s namespace
        shell: bash
        run: |
          ssh ${{ secrets.USER }}@${{ secrets.HOSTNAME }} \
          /snap/bin/microk8s kubectl delete namespace dirtviz-${{ github.event.ref }}

      - name: Remove database
        shell: bash
        run: |
          cat sql/destroy.sql | \
          ssh ${{ secrets.USER }}@${{ secrets.HOSTNAME }} \
          psql -U ${{ secrets.DB_USER }} -d ${{ github.event.ref }}

      - name: Delete environment
        uses: strumwolf/delete-deployment-environment@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          environment: ${{ github.event.ref }}
          ref: ${{ github.event.ref }}
          onlyRemoveDeployments: true
